services:
  app:
    image: danzzan/danzzan-be:latest
    container_name: danzzan-nhn-dev
    network_mode: host
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      KAFKA_BOOTSTRAP_SERVERS: 192.168.0.88:9092
    restart: unless-stopped
